{% set name = "scipyconference" %}
{% set version = "0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scipyconference-{{ version }}.tar.gz
  sha256: 885185abe745ff2039881057189d2db34dc8eab46d14aa24f33a6ade2ab603aa

build:
  entry_points:
    - scipyconf = scipyconference.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - scipyconference
  requires:
    - pip
    - python {{ python_min }}

about:
  license: BSD-3-Clause
  license_file: LICENSE
  home: https://github.com/scipy-conference/puns-scipyconference
  summary: SciPy-community-curated pun package

extra:
  recipe-maintainers:
    - gforsyth
    - bsipocz
